# Generated by Django 6.0.5 on 2026-05-18 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('niveau_acces', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('numero_carte_etudiant', models.CharField(max_length=50, unique=True)),
                ('nb_emprunts_en_cours', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExemplaireLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exemplaire', models.CharField(max_length=50, unique=True)),
                ('etat_physique', models.CharField(max_length=100)),
                ('statut_disponibilite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DemandeEmprunt',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='bibliotheque.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id_emprunt', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('est_prolonge', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliotheque.etudiant')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliotheque.exemplairelivre')),
            ],
        ),
        migrations.AddField(
            model_name='exemplairelivre',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='bibliotheque.livre'),
        ),
    ]
