# Generated by Django 6.0.5 on 2026-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_demandeemprunt_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
