# Generated by Django 6.0.5 on 2026-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeemprunt',
            name='date_retour_prevue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
