# Generated by Django 6.0.5 on 2026-05-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0005_demandeemprunt_date_retour_prevue'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
