# Generated by Django 6.0.5 on 2026-05-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0006_livre_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('logo', models.TextField()),
            ],
        ),
    ]
